env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/errors
    - plugin:react/recommended
    - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
    - prettier
rules:
    react/react-in-jsx-scope: off
    camelcase: error
    spaced-comment: error
    quotes:
        - error
        - single
    no-duplicate-imports: error
    no-debugger: off
    no-console: off
    no-unused-vars: warn
    react/prop-types: warn
settings:
    import/resolver: typescript
    react:
        version: detect
